[tool.poetry]
name = "credcrud"
version = "0.1.0"
description = "Credit Card Crud Microservice"
authors = ["Jonhnatha Trigueiro <joepreludian@gmail.com>"]
license = "Private"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
