"""Create Card entity

Revision ID: 652e07fe64ba
Revises: 3a268a8e823d
Create Date: 2023-11-23 16:36:36.340522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652e07fe64ba'
down_revision: Union[str, None] = '3a268a8e823d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('card_holder', sa.String(length=128), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('cvv', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
